### ISSUE TITLE
Become the fastest ORM in the world

### ISSUE THREAD

**Issue by motin** [propelorm/Propel2#1071]
Propel's basis in code generation makes it possible to optimize the performance specifically to one's data model. 

The query builder can pre-generate most common queries directly into the source code. 

Also, today the classes are generated in PHP, but it is possible to generate them using [zephir](http://docs.zephir-lang.com/en/latest/intro.html#hello-world).

This makes it possible to one day run `propel build` and get the generated classes available via a PHP extension. Since this is not even possible with Phalcon or similar Zephir-based ORM's today, this could potentially make propel the fastest ORM in the world one day. 

Does this sound feasible or am I hoping for too much? :)

Related: https://github.com/propelorm/Propel2/issues/1062 https://github.com/propelorm/Propel2/issues/426 https://github.com/propelorm/Propel2/issues/478

**Comment by SourceCode** [comment]
That's a very interesting idea.  I've thought about these types of approaches for faster implementations over the years as well.  It would be interesting to see something like this happen if the performance improvements really are there.

**Comment by staabm** [comment]
Atm they discuss extensions which can contain code written in php. Even this could get us a bit faster in case the classes would get part of the runtime

**Comment by marcj** [comment]
Yes, that sounds good, but we need first to finish the data-mapper branch because of 

1. we need unit of work to make bulk-inserts/bulk-updates (which even doctrine doesn't support). This is already a big performance boost compared to other ORMs when dealing with much data.
2. we need the [component based building approach](https://github.com/propelorm/Propel2/tree/data-mapper/src/Propel/Generator/Builder/Om/Component) because current huge [ObjectBuilder.php](https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Builder/Om/ObjectBuilder.php) and [QueryBuilder.php](https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Builder/Om/QueryBuilder.php) with 6300+2000 LOC are just way to big. Building on top of those beasts now also a C-Extension-builder will definitely be a PITA.
3.

**Comment by motin** [comment]
@marcj Totally agree. First things first :)

**Comment by bpicolo** [comment]
Just to throw this out there: Please never compile to Zephir. Additional deps is awful. PHP is fast enough these days.

**Comment by marcj** [comment]
Of course not required, but perhaps optional as separate library.

**Comment by dereuromark** [comment]
Closing for now.
