### ISSUE TITLE
Using column aliases in WHERE clause

### ISSUE THREAD

**Issue by TomNoblesse** [propelorm/Propel2#1112]
Hello

Am I overlooking something or can column aliases not be used in the WHERE clause?

Is there a way to make this work? (see below)

**Desired query (example)**

```
SELECT title, char_length(title) AS title_length FROM book WHERE title_length > 4
```

**Fiddle**

http://sandbox.propelorm.org/ad8762d

**Comment by Big-Shark** [comment]
http://sandbox.propelorm.org/dfbf0a3

**Comment by phlopsi** [comment]
It boils down to a limitation of SQL, where the execution order is FROM > WHERE > SELECT for your query, therefore the WHERE clause cannot see aliases created in the SELECT, since it hasn't been executed yet. Some RDBMS might have a way to do this, but that's non-standard SQL as far as i know.

Extending @Big-Shark's example, what i recommend doing for this scenario, is using a PHP variable for the alias, especially for more complex ones:
http://sandbox.propelorm.org/36f6862

**Comment by marcj** [comment]
Yepp, that's not possible due to rdbms limitations.
