### ISSUE TITLE
[idea] OR condition

### ISSUE THREAD

**Issue by Big-Shark** [propelorm/Propel2#1113]
Additions "OR" condition is not very convenient
Example
```php
$books = BookQuery::create()
    ->where('Book.id = ?', 1)
    ->condition('cond1', 'Book.Title = ?', 'War And Peace') // create a condition named 'cond1'
    ->condition('cond2', 'Book.Title LIKE ?', 'War%')       // create a condition named 'cond2'
    ->where(array('cond1', 'cond2'), 'or')                  // combine 'cond1' and 'cond2' with a logical OR
    ->find();
```
```sql
SELECT book.* from book WHERE book.id = 1 AND (book.TITLE = 'War And Peace' OR book.TITLE LIKE 'War%');
```
And I thought, why not change, like so:
Example
```php
$books = BookQuery::create()
    ->where('Book.id = ?', 1)
    ->where(function(BookQuery $query) {
        $query
          ->where('Book.Title = ?', 'War And Peace')
          ->orWhere('Book.Title LIKE ?', 'War%');
    })
    ->find();
```

What do you think about adding a new syntax?
I'm waiting for your comments

**Comment by gharlan** [comment]
refs #613

**Comment by phlopsi** [comment]
Similar to what I have proposed in the referenced isssue https://github.com/propelorm/Propel2/issues/613#issuecomment-175555749, I would approach this the following way:
```php
$books = BookQuery::create()
    ->startWhere()
         ->startOr()
             ->condition('Book.Title = ?', 'War And Peace')
             ->condition('Book.Title LIKE ?', 'War%')
         ->endOr()
    ->endWhere()
    ->find();
```
First of all, being able to call `->where()` multiple looks just wrong, since you can only have one WHERE-clause per FROM-clause in your SQL-query. That's why I chose to introduce a more expressive way, in this case, encapsulating the WHERE-clause with `->startWhere()` and `->endWhere()`. In that block standard concatenation would be AND, so usage of something like `->startOr()` and `->endOr()` is required to change that behaviour. If you have read my other comment you already know that we also need `->startAnd()` and `->endAnd()`. Naming of conditions would need to be made obsolete and removed.

If you need the same condition twice, for whatever edge-case that would be, using a PHP variable is the way to go. There's no need to introduce any additional functionality that just replicates what we already have in a much simpler way ;)

Calling `where()` with one condition would still be possible, being a simple shortcut, but calling it more than once, or calling `startWhere()` should result in an exception. When not trying to break BC multiple `where()` calls are allowed, but it should be mutually exclusive with `startWhere()`.

If startWhere() creates a new object of a different class, the old behaviour could actually just be made obsolete without removing it, if not, creating a new method for that can be another solution for keeeping BC. I do argue, though, that this project being a new major version and still being in alpha, not breaking BC when needed seems like non-sense. This is of course my personal opinion and I do not make those decisions.

**Comment by marcj** [comment]
Dup of https://github.com/propelorm/Propel2/issues/613
