### ISSUE TITLE
Can't replace collection

### ISSUE THREAD

**Issue by ktounet** [propelorm/Propel2#1135]
Hi,

Schema :
```xml
    <table name="bien" phpName="Bien" schema="bien">

        <column name="id" type="integer" primaryKey="true" autoIncrement="true"/>

        <!-- Comportements -->
        <behavior name="timestampable"/>

    </table>

    <table name="bien_assainissement" isCrossRef="true" schema="bien">

        <column name="bien_id" type="integer" primaryKey="true"/>
        <column name="assainissement_id" type="integer" primaryKey="true"/>

        <!-- Relations -->
        <foreign-key foreignTable="bien" onDelete="cascade">
            <reference local="bien_id" foreign="id"/>
        </foreign-key>
        <foreign-key foreignTable="assainissement" foreignSchema="dictionary">
            <reference local="assainissement_id" foreign="id"/>
        </foreign-key>

        <!-- Comportements -->
        <behavior name="sortable"/>

    </table>

    <table name="assainissement" phpName="Assainissement" schema="dictionary">

        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
        <column name="label" type="varchar" required="true" primaryString="true"/>
        
        <!-- Comportements -->
        <behavior name="sortable"/>
        <behavior name="timestampable"/>

    </table>
```

Code :
```php
$a1 = new BienAssainissement();
$a1->setAssainissementId(1);

$bien = new Bien();
$bien->addBienAssainissement($a1);
$bien->save();

// Replace
$a2 = new BienAssainissement();
$a2->setAssainissementId(1);

$coll = new ObjectCollection([$a2]);
$coll->setModel('BienAssainissement');

$bien->setBienAssainissements($coll);
$bien->save(); // SQL error (see below) 
```

Error : 
```sql
Unable to execute INSERT statement [INSERT INTO bien.bien_assainissement (bien_id, assainissement_id, sortable_rank) VALUES (:p0, :p1, :p2)]
```

This error occurs because the first object ```$a1``` is still present into the table.

The problem is that both ```hashCode``` generated from the composite primary key for ```$a1``` and ```$a2``` are exactly the same.

Since https://github.com/propelorm/Propel2/pull/1027, the elements scheduled for deletion can be now kept.

The object ```$a1``` is not deleted from database, it's removed from "xxxScheduledForDeletion" due to https://github.com/propelorm/Propel2/pull/1027/files#diff-9b07d46f22d6e0c7cfe06394bc978cc5R3769. The previous function ```$this->{$scheduledForDeletion}->contains(\$l)``` returns true because of the ```hashCode```.

I hope I was clear enough...

**Comment by marcj** [comment]
Yes, the "issue" is that hashCode generate the same, but that's not a bug, rather intended. Why don't you  just change `$a1` the way you want `$a2` to be? If you have two instances that have in their domain the same identifier then Propel can't do anything to resolve it because your responsible that those two instances differ in their identity or behave exactly the same (which means there may not be two instances  in the memory which one of it has a state `saved` and the other not, which reflects basically a broken state, made by yourself). So two solutions:

1. change $a1 the way you want and do not add another BienAssainissement which has the same identifier.
2. Delete  $a1, and then create a new relation=.

**Comment by ktounet** [comment]
Ok, both solutions suits me. Thanks.
