### ISSUE TITLE
return ID on duplicate

### ISSUE THREAD

**Issue by roydekleijn** [propelorm/Propel2#1177]
Hi,
How to return the ID of a existing record when inserting a duplicate ?

Previously I used:
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)

How can I implement something similar using Propel?

I have a one-to-many implementation with a join table.

something like this:
```
Table post
id | int | pk
title | varchar
body | text

Table tag
id | int | pk
tagname | varchar

Table post_tags (join table)
post_id | int
tag_id | int
```

Roy

**Comment by marcj** [comment]
That's unfortunately not possible. You should make sure that ID is unique beforehand.

**Comment by roydekleijn** [comment]
ok, but also are jointables not possible ?

**Comment by marcj** [comment]
What do you mean by that?

**Comment by roydekleijn** [comment]
like the example tables I made: 

Table post
id | int | pk
title | varchar
body | text

Table tag
id | int | pk
tagname | varchar

Table post_tags (join table)
post_id | int | key to post table
tag_id | int | key to tag table

**Comment by marcj** [comment]
I don't get what you mean. Yo want to link `tag` and `post` and do not check if its already linke, so it will crash with duplicate keys?

**Comment by roydekleijn** [comment]
when using plain PDO, I tried to insert a tag. The id was returned if the tag already exists.
how to achieve (more or less) the same with Propel? or is it really necessary to retrieve the ID first ?

what do you suggest ?

**Comment by marcj** [comment]
Why don't you use autoIncrement on the tag id?

**Comment by roydekleijn** [comment]
because in the tag table we have an almost fixed set of tags...

and the post_tags (join table) joins tags to posts. Like
https://www.google.nl/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fd%2Fd7%2FMapping_table_concept.png&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAssociative_entity&docid=5giK1h-Z49WRkM&tbnid=fird7-uNUuoboM%3A&w=510&h=256&bih=708&biw=1440&ved=0ahUKEwiSyLn2lb7MAhVELMAKHf7_CYAQMwgvKBIwEg&iact=mrc&uact=8

On Tue, May 3, 2016 at 4:39 PM, Marc J. Schmidt <notifications@github.com>
wrote:

> Why don't you use autoIncrement on the tag id?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/propelorm/Propel2/issues/1177#issuecomment-216549809>
>



-- 


[image: --]
Roy de Kleijn
[image: http://]about.me/roydekleijn
<http://about.me/roydekleijn?promo=email_sig>

**Comment by marcj** [comment]
So, to recap: You want to add tags using Propel, but you don't know beforehand whether a tag id exists or not? Why don't you just check beforehand? And if not exists, add it, when exists update.

> or is it really necessary to retrieve the ID first ?

Yes.

**Comment by roydekleijn** [comment]
ok, will do it like that ....

I thought propel had some similar as Doctrine (
http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/association-mapping.html#one-to-many-unidirectional-with-join-table
)

On Tue, May 3, 2016 at 6:40 PM, Marc J. Schmidt <notifications@github.com>
wrote:

> So, to recap: You want to add tags using Propel, but you don't know
> beforehand whether a tag id exists or not? Why don't you just check
> beforehand? And if not exists, add it, when exists update.
>
> or is it really necessary to retrieve the ID first ?
>
> Yes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/propelorm/Propel2/issues/1177#issuecomment-216588741>
>



-- 


[image: --]
Roy de Kleijn
[image: http://]about.me/roydekleijn
<http://about.me/roydekleijn?promo=email_sig>

**Comment by marcj** [comment]
What has a one-to-many using unidirectional join table to do with your issue about "How to return the ID of a existing record when inserting a duplicate"? You showed me a picture about a many-to-many relation and now you refer to a one-to-many relationship. I honestly can't follow you nor understand what you really need.

**Comment by SourceCode** [comment]
I would do your initial insert into "post" then gather the objects (records) of the existing tags to be added and then do those inserts for the association and then also do new inserts for the new tags and then insert the records for those associations again using the objects returned.  (Notice that all your query classes support using the object vs the value/key) .

In these situations I actually have a pattern where I check the associations as well in my joining table.  I first set all of them to inactive (via a status field used in all my tables) and then reactivate what needs activating (existing) and then insert and add an association for anything that didn't already exist.

While you can optimize it further in native MySQL via the ON DUPLICATE KEY UPDATE I'm not sure if that is something that is actually possible across the supported database systems of Propel currently.  I could be wrong, but I haven't seen anything that leads me to believe something currently exists. 

Perhaps by building a custom behavior yourself you can support this?  See: http://propelorm.org/documentation/06-behaviors.html#writing-a-behavior

I would suggest to submit questions at sites like [stackoverflow](http://stackoverflow.com/) to really get help, this is more a place for reporting issues rather than getting dev advice in my opinion (not sure the policy of the project in this regard).
