### ISSUE TITLE
Migration fails on a modular approach (packaged schema.xml)

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1209]
I realized a problem with migration and a packaged schema.xml. Following situation:

3 packages; 3 schema files (By package I mean composer package):

1. `Package Base`: schema file: `base-schema.xml`
2. `Package A`: requires Package Base; schema file: `a-schema.xml` -> external schema: `Package Base/base-schema.xml`
3. `Package B`: requires Package Base; schema file: `b-schema.xml` -> external schema: `Package Base/base-schema.xml`

Now, If I run a `propel diff` in either Package A or B, it wants to delete tables from the other package, It also takes changes from base-schema.xml into account (In my case, I'd like that not to happen). In my situation, it should only track changes for diffs happening in the schema file for each package. Others might for sure prefer different handling.

This situation can also be expanded:
`Package C`: requires Package B; schema file: `c-schema.xml` -> external schema: `Package B/b-schema.xml`

**Comment by marcj** [comment]
This works as intended. Propel compares database model with the real database. If your database model has some missing tables because you use some kind of modular stuff then you need to make sure they are either in the database model anyway or skip those tables. There's no logical way Propel can follow to not drop your tables in the other package since Propel doesn't know anything about your "module approach".
If you want to exclude some tables from that process you can use `skip-tables` option. If you want to completely remove that drop table handling use `skip-removed-table`.

**Comment by gossi** [comment]
Yes I understand. Any way to maybe extend this in the future, that `migration diff` only handles the schema file from the config (and doesn't follow external-schema)? (Although, yes, I see the problematic of getting a proper reference between the current schema.xml model and the state before)
