### ISSUE TITLE
Propel Instance Pool

### ISSUE THREAD

**Issue by gulaandrij** [propelorm/Propel2#1247]
Look sandbox
http://sandbox.propelorm.org/ba0727a
First product without rating generate 5 queries, and second, with rating, just 1. It's bug or that's ok?

**Comment by gulaandrij** [comment]
@marcj ?

**Comment by mpscholten** [comment]
Looks like a bug to me. Would be cool if you can provide a PR for fixing this.

**Comment by gulaandrij** [comment]
I dont know how to fix this

**Comment by Alekc** [comment]
This issue (although I always though it was a feature, and got around it) usualy comes out when you left join a child .

If you take a look inside getSProductsRating you will see 
```code
    public function getSProductsRating(ConnectionInterface $con = null)
    {

        if ($this->singleSProductsRating === null && !$this->isNew()) {
            $this->singleSProductsRating = ChildSProductsRatingQuery::create()->findPk($this->getPrimaryKey(), $con);
        }

        return $this->singleSProductsRating;
    }
```

So if child (in this case sproductRating) is null (because it's either doesn't exist at all or have not yet been fetched), a query is performed. 

The issue is that since the child doesn't exist, `$this->singleSProductsRating ` will always be null, so if you call for it again on the same instance, then you will perform query again. 

Usually my workaround is to add following function to model class (in my example for getPresence() function which should return a child if exists)
```php
    /**
     * Returns presence only if it's already has been merged into through query.
     * It WILL NOT run a query
     *
     * @return Presence
     */
    public function getPresenceIfExists()
    {
        return $this->singlePresence;
    }
```

**Comment by gulaandrij** [comment]
can some one provide fix for this?

**Comment by marcj** [comment]
It's not a bug. Since the first query results always null and [NULL's are not cached](https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Builder/Om/ObjectBuilder.php#L3654) it executes always new queries against the database.
