### ISSUE TITLE
Foreign Tables with two primary keys throw a error on build

### ISSUE THREAD

**Issue by aldos84** [propelorm/Propel2#1380]
I've a table for localization with 2 primary keys
```
<table name="i18n">
        <column name="id" type="INTEGER" required="true" primaryKey="true" autoIncrement="false"/>
        <column name="locale" type="VARCHAR" required="true" primaryKey="true" size="6"/>
        <column name="text" type="CLOB" required="true"/>
</table>
```

Another table has only a foreign key to the id
```
<table name="page">
        <column name="body_id" type="INTEGER" required="true"/>
        <foreign-key foreignTable="i18n" phpName="Body" onDelete="cascade">
            <reference local="body_id" foreign="id"/>
        </foreign-key>
</table>
```

Since the last update, if i run "propel build" i get this error exception

>   [Propel\Generator\Exception\BuildException]                                    
>   Table "page" contains a foreign key to table "i18n" but does not have a reference to foreign primary key "locale"

How i can resolve this without changing my whole localization concept?

**Comment by marcj** [comment]
Well, your localization concept is broken since the relation from Page to i18n is not n:1, but n:n, since `id` alone in i18n is not unique. If you query `i18n WHERE id = 1` it could return multiple items. In foreign keys you should make sure to use as `reference` the foreign full primary key. 
If `i18n:locale` is not part of the primary key, remove it from the primary key and introduce a unique constraint over both `id` and `locale` if that is necessary.

**Comment by aldos84** [comment]
yeah, i see it foreign keys make no sense and i don't use it actually. So i will remove this foreign keys and hope the building process works.

Thx
