### ISSUE TITLE
[Possible bug] No connection defined for database "default"

### ISSUE THREAD

**Issue by xiurobert** [propelorm/Propel2#1423]
Running propel init, and generating the config.php which looks normal. However, upon including this config.php in my web application, I get greeted with this beautiful error message:

```
Fatal error: Uncaught Propel\Runtime\Exception\RuntimeException: No connection defined for database "default". Did you forget to define a connection or is it wrong written? in 

C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ServiceContainer\StandardServiceContainer.php:279 Stack trace: #0 

C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ServiceContainer\StandardServiceContainer.php(372): Propel\Runtime\ServiceContainer\StandardServiceContainer->getConnectionManager('default') #1 

C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\ModelCriteria.php(1018): Propel\Runtime\ServiceContainer\StandardServiceContainer->getReadConnection('default') #2 

C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\ModelCriteria.php(1317): Propel\Runtime\ActiveQuery\ModelCriteria->findOne(NULL) #3 [internal function]: Propel\Runtime\ActiveQuery\ModelCriteria->findOneBy('Key', 'infini in 

C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ServiceContainer\StandardServiceContainer.php on line 279
```
Is there a fix for this or is this a bug?

**Comment by cristianoc72** [comment]
It seems that in your schema.xml the database name is "default" but in your
configuration file there is no connection named "default".

Il 11/ott/2017 14:33, "xiurobert" <notifications@github.com> ha scritto:

Running propel init, and generating the config.php which looks normal.
However, upon including this config.php in my web application, I get
greeted with this beautiful error message:

Fatal error: Uncaught Propel\Runtime\Exception\RuntimeException: No
connection defined for database "default". Did you forget to define a
connection or is it wrong written? in
C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ServiceContainer\StandardServiceContainer.php:279
Stack trace: #0
C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ServiceContainer\StandardServiceContainer.php(372):
Propel\Runtime\ServiceContainer\StandardServiceContainer->getConnectionManager('default')
#1 C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\ModelCriteria.php(1018):
Propel\Runtime\ServiceContainer\StandardServiceContainer->getReadConnection('default')
#2 C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\ModelCriteria.php(1317):
Propel\Runtime\ActiveQuery\ModelCriteria->findOne(NULL) #3 [internal
function]: Propel\Runtime\ActiveQuery\ModelCriteria->findOneBy('Key',
'infini in C:\Users\Robert\Documents\GitHub\InfiniaHome\vendor\propel\propel\src\Propel\Runtime\ServiceContainer\StandardServiceContainer.php
on line 279

Is there a fix for this or is this a bug?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/propelorm/Propel2/issues/1423>, or mute the thread

**Comment by xiurobert** [comment]
Config.php is available [here](https://github.com/InfiniaPress/InfiniaHome/blob/master/infiniahome/generated-conf/config.php)

**Comment by xiurobert** [comment]
My bad, hit the wrong button

**Comment by marcj** [comment]
Can you post the actual code from that stack trace? I doubt that StandardServiceContainer.php: 372 is triggering a model query. I guess that trace is somehow wrong.

**Comment by xiurobert** [comment]
All the code is located in the repository where I linked the file above or (here)[https://github.com/InfiniaPress/InfiniaHome]

**Comment by marcj** [comment]
Where do you include the Propel's php config?

**Comment by xiurobert** [comment]
https://github.com/InfiniaPress/InfiniaHome/blob/master/infiniahome/index.php#L12

**Comment by xiurobert** [comment]
Error resolved. Forgot to require the configuration file in my routing application. Apparently requiring it in the index file isn't enough. Weird

**Comment by karthibca28** [comment]
I have same issue plz tell me how to solve tis?


#0 /var/www/html/My_project/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1936): Propel\Runtime\ActiveQuery\Criteria->doSelect(Object(Propel\Runtime\Connection\ConnectionWrapper))
#1 /var/www/html/My_project/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1006): Propel\Runtime\ActiveQuery\ModelCriteria->doSelect(Object(Propel\Runtime\Connection\ConnectionWrapper))
#2 /var/www/html/My_project/database/classes/my_site/db/my_site/PvActivation.php(107): Propel\Runtime\ActiveQuery\ModelCriteria->findOne()
#3 /var/www/html/My_project/database/classes/my_site/db/my_site/PvActivation.php(76): my_site\db\my_site\PvActivation->makeNewActId(1)
#4 /var/www/html/My_project/database/classes/my_site/db/my_site/PvUser.php(1626): my_site\db\my_site\PvActivation->activateLogin(1, '')
#5 /var/www/html/My_project/database/classes/my_site/db/my_site/PvUser.php(1610): my_site\db\my_site\PvUser->makeLoginResponse(true, Object(my_site\db\my_site\PvUser))
#6 /var/www/html/My_project/api/player/ProfileController.inc(146): my_site\db\my_site\PvUser->makeLogin('admin', '2345673', 0)
#7 [internal function]: my_site\api\ProfileController->profileLogin()
#8 /var/www/html/My_project/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#9 /var/www/html/My_project/vendor/slim/slim/Slim/Slim.php(1343): Slim\Route->dispatch()
#10 /var/www/html/My_project/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#11 /var/www/html/My_project/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#12 /var/www/html/My_project/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#13 /var/www/html/My_project/vendor/slim/slim/Slim/Slim.php(1288): Slim\Middleware\PrettyExceptions->call()
#14 /var/www/html/My_project/site/slim.php(121): Slim\Slim->run()
#15 {main}
