### ISSUE TITLE
New Feature Request: EventDispatcher based behavior implementation

### ISSUE THREAD

**Issue by tboerger** [propelorm/Propel2#144]
It would be nice to write behaviors based on an event dispatcher. That way the behavior generator listens to specific events and injects the code on the correct place. That event driven implementation im combination with twig templates would be awesome!

**Comment by bryanlatten** [comment]
+1 (glad I was able to find this older one)

I think there are two different concerns. The method conventions are great for maintaining relationships with other models, but I believe the author (and myself) are looking to bind more domain action to CRUD activity. For example, on model create, you could see a case to send email, reindex remote search indexes, etc. (post the transaction, of course). I would *not* want to bake that logic into a `post***` model function, but instead, have that model simply dispatch an event that other components can externally bind to. 

I've implemented this jankily, so hopefully you could point me a better way. Setting dependencies on a model class either via constructor or `set` method is not guaranteed, since there are raw `new` calls to create those models in the mapper class. Any suggestions on how to guarantee a dependency (like event dispatcher) into a model at runtime?

**Comment by marcj** [comment]
Hey Bryan, this issue is about an event dispatcher during build time for behavior clases, not for runtime. Whay you mean is an event dispatcher during runtime: we have this in the data-mapper branch in development.

**Comment by bryanlatten** [comment]
@marcj thanks for the fast response - i'll check it out for sure!

**Comment by marcj** [comment]
Unfortunately not yet, since its in active development.

**Comment by bryanlatten** [comment]
No worries, happy to build/test/give feedback if you need

**Comment by marcj** [comment]
Sure :) but you will definitely run into troubles since not everything have been ported/developed yet (relation stuff, behaviors, ...)

**Comment by tboerger** [comment]
I'm not using it for ages and lost the interest.
