### ISSUE TITLE
Passing an Active PDO connection to propel or extract it from propel

### ISSUE THREAD

**Issue by ArabCoders** [propelorm/Propel2#1481]
Hello,

I'm in the process of migrating codebase to use Propel, so i managed to generate the models and everything is fine, however im at loss at how to pass an active PDO connection to propel, or extract one from it, so we dont use double connection for each visiting user.

The codebase type hint \PDO and we cant hack it to use ConnectionInterface provided by Propel,

Is it possible to extract the active PDO connection from propel or pass one to it ?

PS: sorry if this question came up before, i searched the issues and i was unable to find any reference to it.
Thank you.

**Comment by dereuromark** [comment]
Is this still relevant or can it be closed?

**Comment by ArabCoders** [comment]
@dereuromark Hi, i no longer work on that project you can go ahead and close it if you feel it's no longer needed.

Thank you.

**Comment by dereuromark** [comment]
https://github.com/propelorm/Propel2/pull/1611 will be a stab into decouling using an adapter
This is required anyway since PHP8 will introduce hard typehints that PHP7 disallows. So in order to have compatibility for both we will need this.
Closing then as the PR will be further worked to get PHP7+8 working soon.
