### ISSUE TITLE
Syfmony 4.1 + How to generate model

### ISSUE THREAD

**Issue by parthiv2585** [propelorm/Propel2#1494]
Hi All,

I have upgrade Symfony 3.4 ( Propel ORM ) to Symfony 4.1 (Propel ORM). 
(1) Where i have to create schema.xml fille ?
(2) How to  generate models ?

Thanks 

Parthiv Shah

**Comment by cristianoc72** [comment]
Hi,
1. install Propel Bundle: `composer require propel/propel-bundle 4.0@dev`
2. create `src\propel` path and put your schema.xml there
3. in your `config\packages` directory, create your propel.yaml configuration file
4. Build your model via PropelBundle commands: `bin/console propel:build`

Good luck!

**Comment by parthiv2585** [comment]
Thanks 
Issue is fixed. 
I have generated model in "Entity" folder and get below error.

Attempted to load class "ActivityLogQuery" from namespace "App\Controller\App\Entity".
Did you forget a "use" statement for "App\Entity\ActivityLogQuery"?

```
<database name="yoursource" defaultIdMethod="native" namespace="Entity"> 
<table name="activity_log" idMethod="native" phpName="ActivityLog">
    <column name="activity_log_id" phpName="ActivityLogId" type="INTEGER" primaryKey="true" autoIncrement="true" required="true"/>
    <column name="activity_type_id" phpName="ActivityTypeId" type="INTEGER" required="true" defaultValue="1"/>
</table>
</database>
```
 
Please help.

Thanks you so much for quick help.

**Comment by cristianoc72** [comment]
`Did you forget a "use" statement for "App\Entity\ActivityLogQuery"?`

It's not a Propel issue: get a look in your controller.

**Comment by parthiv2585** [comment]
Thanks you so much but i have added but still not working. Please check my controller code.

```
namespace App\Controller;

use Entity;
use Entity\Person;
use Entity\PersonQuery;

class PersonController extends AbstractController 
{
	public function logincheckAction(Request $request) {
		$person = PersonQuery::create()->filterByEmail($email)->findOne();
	}	
}
```

All Model generated in src->Entity , src->Entity->Base , src->Entity->map.

Thanks.

**Comment by cristianoc72** [comment]
Ah, ok. If you use the composer Symfony project autoloader, it associates the directory `src/Entity` to `App\Entity` namespace.
So change the first line of your schema.xml as follow;

`<database name="yoursource" defaultIdMethod="native" namespace="App\Entity">`

and rebuild your model.
Now, in your controllers write: 
```php
namespace App\Controller;

use App\Entity\Person;
use App\Entity\PersonQuery;

class PersonController extends AbstractController 
{
	public function logincheckAction(Request $request) {
		$person = PersonQuery::create()->filterByEmail($email)->findOne();
	}	
}
```

Tip: since the directory `src/Entity` is used by Doctrine, I prefer to put Propel classes in `src/Model` path.
To do it, just write (in your schema.xml): `<database name="yoursource" defaultIdMethod="native" namespace="App\Model">` and rebuild your model. Propel creates for you the directory and the classes.

**Comment by parthiv2585** [comment]
Thanks you so much.Now issue is fixed.
