### ISSUE TITLE
State of this project / Fork

### ISSUE THREAD

**Issue by GBeushausen** [propelorm/Propel2#1524]
After submitting a pull request, i noticed that there are 46 open pull requests. Is nobody even accepting contributions for this project anymore?

I've read the statement, that they are shifting to Propel 3, but i can't agree with this mentality. It's never a good idea to start over and completly rewrite your project. Chances are high, that this will be the end of it. 

Also i don't see much sense in stating that ActiveRecord is not modern anymore. This is not fashion. I have many commercial projects, that rely on Propel2. And i think it's a great peace of software which offers a better over all solution than any other ORM. 

So if this project is dead for real, who's in for creating a fork and keep Propel 2 going under a new name? 

@marcj

**Comment by marcj** [comment]
> Is nobody even accepting contributions for this project anymore?

Correct. Propel2 is a enormously complex peace of software because it covers so many concerns and functionality. Managing PRs mean you have to have constantly in your mind all implications that new code brings in. Just merging without caring about side effects is easy. Keeping the quality up is hard work. And it's an unrealistic goal if you don't even use the library anymore in your own projects, even more if you don't use that PHP technology as whole anymore.

Feel free to create a fork and merge all pull-requests there. I'm more than happy to link to it once the fork reached a release and when it has same feature-set. But to be honest, why would someone invest time creating a fork and redo all the release/doc stuff, when they can just take over the project? We're looking for a new maintainer for years, but nobody wanted to invest that time. I mean here as well, taking the position is easy, but doing the actual work is a tough job. And you don't even need a position title or permission in order to handle issues, test PRs, give feedback, etc. Obviously nobody wanted to do it. What could be the reason for this is left to speculation.

> I've read the statement, that they are shifting to Propel 3, but i can't agree with this mentality.

You don't have to agree, that's ok.

> It's never a good idea to start over and completely rewrite your project. 

That's where I disagree :)

> Chances are high, that this will be the end of it.

That (Propel2 death) was the sole purpose of creating Propel 3. But latter died due to same reason as v2: Lack of contribution for a really sophisticated project that doesn't subsidize its work in any way.

It was even tried to find sponsors for the project, but nobody wanted to pay for it. So there it goes: A project where people contribute PRs, sometimes event without comments, just throw in code. Nobody checks PRs, nobody checks issues, nobody wants to pay, usage decreases. I can only summarize with: Propel had its best time and many people invested hundred of thousands dollars in it. That changed and it's time to move on.

> Also i don't see much sense in stating that ActiveRecord is not modern anymore. This is not fashion.

Code **is** like fashion. And ActiveRecord has its objective flaws.

> I have many commercial projects, that rely on Propel2.

Guess what: I invested many ten thousand $ and you earn with it money. It's either time to invest back or let the project die. Complaining why someone else does not want to do even more free work is not enough. Taking action is the only way to keep it alive.

**Comment by GBeushausen** [comment]
@marcj WHAT? You don't want to do more free work, so i can make money off of it? Shame on you :-)

No i can understand where you're coming from. For me it's just that i have many commercial projects relying on Propel and i think it's very good for what it does. Still better than what most other ORMs offer. But no customer in the world is paying me to migrate to another ORM, because they won't get anything out of it. Customers only pay for features.

So i would be willing to help out this project and merge the PRs and fix at least the issues, my customers are paying for. May not be much, but at least better than it is now.
