### ISSUE TITLE
Cannot use "parent" when current class scope has no parent

### ISSUE THREAD

**Issue by oojacoboo** [propelorm/Propel2#1528]
With 7.4 on the base models, the lifecycle callbacks use the `parent` keyword.  However, there isn't a parent class.

`Cannot use "parent" when current class scope has no parent`

I'm unsure if Propel is doing anything fancy that'd allow this code to actually execute properly.  Why is this written the way it is?  Can it be safely removed?  Is it possible to refactor this without being a huge rewrite?

**Comment by tspink** [comment]
I too encountered this problem - but I think it might have something to do if you are using concrete table inheritance.  I quickly tested this:
```
<database name="test" defaultIdMethod="native" namespace="TestDB">
    <table name="base_table" phpName="BaseTable">
        <column name="base_table_id" required="true" primaryKey="true" autoIncrement="true" />
        <column name="base_table_field" type="integer" required="true" />
    </table>

    <table name="sub_table" phpName="SubTable">
        <column name="sub_table_field" type="integer" required="true" />
        <behavior name="concrete_inheritance">
            <parameter name="extends" value="base_table" />
        </behavior>
    </table>
</database>
```

And this generated:
```abstract class SubTable extends ChildBaseTable```

Which means that the code would be valid, when using the concrete table inheritance feature.

I'm assuming the reason it's done this way is because there is a single code template that (until now) worked for both the inherited and non-inherited cases.  With 7.4 being stricter, the dynamic guard is not enough to prevent static analysis from seeing the call to ```parent::```

A "proper" fix would probably be to have two templates, one for models that utilise concrete table inheritance, and one for models that do not, then emit the corresponding template as appropriate.  Arbitrarily removing this code would break pre-/post- functions for inherited table models, but have no effect on non-inherited models.

**Comment by oojacoboo** [comment]
@tspink nice find.  We've had to fork Propel at this point and clean up all kinds of things for 7.4.  We ended up just removing this from the templates and regenerated our models.

It'd be nice if this repo wasn't dead, or was turned over to someone else.  @marcj any chance of that happening?  Maybe update the docs?

**Comment by tspink** [comment]
If anyone's interested, I fixed this issue like this:
https://github.com/tspink/Propel2/commit/ab02b3d4e84101e57b781d3aff9ea38fa1140e10

And somewhat embarassingly with this (always test before you commit!):
https://github.com/tspink/Propel2/commit/9cb499ae6ef73ab42796f037666c6ff1077a8f78

It seems to work correctly - although I messed up the tabbing in the template.

**Comment by dereuromark** [comment]
Are you able to make a PR here?

**Comment by tspink** [comment]
Hi,

I merged the two commits for this particular into one, and popped it in a dev branch on my fork. This is now submitted as PR #1542 

-- Tom

**Comment by PhilinTv** [comment]
Resolved. Thanks @tspink !
