### ISSUE TITLE
Add synfony 5 compatibility

### ISSUE THREAD

**Issue by Snake231088** [propelorm/Propel2#1534]
Add synfony 5 compatibility

**Comment by acabutto** [comment]
+1

**Comment by spartan** [comment]
+1

**Comment by dereuromark** [comment]
PR open: https://github.com/propelorm/Propel2/pull/1536
Is it confirmed by someone that it fully works?

**Comment by dereuromark** [comment]
We now have master almost green ( https://travis-ci.org/github/propelorm/Propel2 )
Help of the community is greatly appreciated in terms of getting all Travis build jobs green.

As for this issue, we opened a follow up ticket now and it turns out this lib is not really fully compatible with Symfony 5 yet. Some bugs need fixing.
If anyone could open a PR here that would be greatly appreciated.

**Comment by dereuromark** [comment]
Closing in favor of main ticket https://github.com/propelorm/Propel2/issues/1578
