### ISSUE TITLE
Propel contribution / collaboration ?

### ISSUE THREAD

**Issue by dereuromark** [propelorm/Propel2#1707]
Hi Propel community

We from Spryker have been helping out in maintaining this project the last months.
From the PRs coming in it seems also others have noticed some momentum moving forward.
Together we did PHP8 compatibility and added new features as well as bugfixes.

That said, we see a lot of PRs that only we check and review, though.
It would be best for the community if also others would help to review and check incoming issues and PRs.
This way we make sure that we use our collective knowledge to merge highest quality of changes.
It would also help us, as right now we need to spend a bit more resources or will take more time (weeks).

So please feel welcome to check the open PRs that are green (CI OK) and look ready for review.
You can always use @propelorm/propel2-spryker-dev-team  to ping us if want additional input on a topic.

If you have any ideas how we could collaborate more effectively, we can use this ticket to share ideas.
Thank you!

**Comment by damoclark** [comment]
Hi @dereuromark 

I would dearly like to see Propel revived for new projects requiring an ORM as I previously found it a pleasure to work with.  Recently I have been working with Doctrine2, and I am perpetually frustrated with how onerous it is to use by comparison.  The sort of work I do is more focused on rapid prototyping and experimenting with new ideas and Propel has typically been a productive and intuitive fit for this.  My mantra is along the lines of making the simple things easy and the difficult things possible (i.e. Perl).  Doctrine2, for me, achieves neither.

Praise aside, I work for an Australian University and we offer both Undergraduate and Postgraduate IT degrees.  There is the potential to have students contribute to Propel either as project work credited towards their degree, or otherwise, extra-curricular work experience on a real open source project.  

I am not proposing any commercial activity.  Just to explore a win/win possibility for the Propel project and our students.  Mark, would you be interested in further dialogue about possibilities here?  I understand if not.  But if so, let me know and we can discuss over email.

Cheers,
Damien.

**Comment by nederdirk** [comment]
Hi @dereuromark ,
you may have seen a couple of PRs from my hand lately. At my employer's we use Propel2 as a DB abstraction/ORM, and I often feel the urge to try to fix things upstream (mostly in the static analysis department).
I would have to put maintenance work on the fringes of my calendar, but I might find the time for a maintainers-chat (e.g. once every two weeks) to align who will take responsibility for which open issues/PRs.

Something that could be helpful, in my opinion, is deciding on some process for issues and PRs. I've found it frustrating a couple of times to have submitted a PR, which received an 'approved' stamp (usually from @dereuromark :raised_hands: ), but then it just sat there for a while. During those times, I was confused about whether I should nag, patiently wait, or if some action on my part was still required.

Peace and good,
Dirk

**Comment by dereuromark** [comment]
@nederdirk The main reason is that we got to an understanding of a minimum of 2 approvals per PR for merge :)
In other words: I am not allowed to merge without enough approvals.
So thats also why I opened this discussion - as without other people doing at least some basic checking and approving, those would then sit much longer, or never get merged.

**Comment by nederdirk** [comment]
> @nederdirk The main reason is that we got to an understanding of a minimum of 2 approvals per PR for merge :)
> In other words: I am not allowed to merge without enough approvals.

I didn't know that, but it clarifies a lot!

**Comment by mringler** [comment]
Hi @dereuromark,

thank you for the post, this clears a lot of things up for me.

Is it possible to have Github add an auto-generated message to new pull requests, notifying about workload issues? I think this would have helped me understand how the project works, and probably helps to get people involved. Something like 

> Thank you for your contribution to Propel. As Propel is an open-source project, we depend on your participation. We will try to review and process your pull request as fast as possible. 
>
> To our dismay, we currently have not enough reviewers to guarantee a fast progress, but we will try our best and hope to get back to you within the next two weeks.
> To speed things up, please make sure you have added working test cases for your changes, and that all tests complete successfully.
>
> If you want to review other requests, you could help us out a lot, too.
>
> Again, thank you for your contribution!

Looking at the PRs, it is hard for me to figure out which of them are still active. They go back to 2014, which is probably not relevant anymore. Closing those, if the author does not respond within a month, would help to clean things up, too.

Thank you for all the work you have put into Propel!

Best,
Moritz

**Comment by dereuromark** [comment]
OK, in that spirit I will close this now - and let's all contribute, review and approve PRs :)
