### ISSUE TITLE
Typecast on Om/TableMapBuilder.php#L849 causes issues with user defined phpType

### ISSUE THREAD

**Issue by rovangju** [propelorm/Propel2#926]
## Synopsis

When using a custom userspace column php datatype, the generator creates a typecast that doesn't work.
### Example schema entry

```
<table name="_operator" idMethod="native" phpName="Operator">
    <column name="id" phpName="Id" phpType="\api\utility\ShaId" type="VARCHAR" size="20" sqlType="binary(20)" primaryKey="true" required="true"/>
    <column name="name" phpName="Name" type="VARCHAR" size="120" require="true"  />
</table>
```
### Yields (OperatorTableMap.php ~@L189)

```
    return (\api\utility\ShaId) $row[  // <-- This part. 
        $indexType == TableMap::TYPE_NUM
            ? 0 + $offset
            : self::translateFieldName('Id', TableMap::TYPE_PHPNAME, $indexType)
    ];
```

**Comment by marcj** [comment]
Fair enough, this is indeed a bug, because the value isn't correctly casted to a string representation. But, just to give you note: I'd definitely not use a serialised object as primary key. Especially if you use some kind of uuid or other lenghty IDs you should store them as binary and rearrange its structure to not suffer from performance issues later. https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/

**Comment by rovangju** [comment]
FWIW it's for a callback to translate hex SHA1 into binary(20) and back to string.
